QT -= gui
QT += network serialport
greaterThan(QT_MAJOR_VERSION, 4):
CONFIG += c++11 console
CONFIG -= app_bundle

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        ../connection.cpp \
        ../debug_emulator.cpp \
        ../mavsys.cpp \
        ../messagehandler.cpp \
        ../serialconnection.cpp \
        ../udpconnection.cpp \
        main.cpp \
        uavmessagehandler.cpp

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

SUBDIRS += \
    ../ground_station.pro

HEADERS += \
    ../connection.h \
    ../debug_emulator.h \
    ../include/checksum.h \
    ../include/common/common.h \
    ../include/common/common.hpp \
    ../include/common/gtestsuite.hpp \
    ../include/common/mavlink.h \
    ../include/common/mavlink_msg_actuator_control_target.h \
    ../include/common/mavlink_msg_actuator_control_target.hpp \
    ../include/common/mavlink_msg_actuator_output_status.h \
    ../include/common/mavlink_msg_actuator_output_status.hpp \
    ../include/common/mavlink_msg_adsb_vehicle.h \
    ../include/common/mavlink_msg_adsb_vehicle.hpp \
    ../include/common/mavlink_msg_ais_vessel.h \
    ../include/common/mavlink_msg_ais_vessel.hpp \
    ../include/common/mavlink_msg_altitude.h \
    ../include/common/mavlink_msg_altitude.hpp \
    ../include/common/mavlink_msg_att_pos_mocap.h \
    ../include/common/mavlink_msg_att_pos_mocap.hpp \
    ../include/common/mavlink_msg_attitude.h \
    ../include/common/mavlink_msg_attitude.hpp \
    ../include/common/mavlink_msg_attitude_quaternion.h \
    ../include/common/mavlink_msg_attitude_quaternion.hpp \
    ../include/common/mavlink_msg_attitude_quaternion_cov.h \
    ../include/common/mavlink_msg_attitude_quaternion_cov.hpp \
    ../include/common/mavlink_msg_attitude_target.h \
    ../include/common/mavlink_msg_attitude_target.hpp \
    ../include/common/mavlink_msg_auth_key.h \
    ../include/common/mavlink_msg_auth_key.hpp \
    ../include/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
    ../include/common/mavlink_msg_autopilot_state_for_gimbal_device.hpp \
    ../include/common/mavlink_msg_autopilot_version.h \
    ../include/common/mavlink_msg_autopilot_version.hpp \
    ../include/common/mavlink_msg_battery_status.h \
    ../include/common/mavlink_msg_battery_status.hpp \
    ../include/common/mavlink_msg_button_change.h \
    ../include/common/mavlink_msg_button_change.hpp \
    ../include/common/mavlink_msg_camera_capture_status.h \
    ../include/common/mavlink_msg_camera_capture_status.hpp \
    ../include/common/mavlink_msg_camera_fov_status.h \
    ../include/common/mavlink_msg_camera_fov_status.hpp \
    ../include/common/mavlink_msg_camera_image_captured.h \
    ../include/common/mavlink_msg_camera_image_captured.hpp \
    ../include/common/mavlink_msg_camera_information.h \
    ../include/common/mavlink_msg_camera_information.hpp \
    ../include/common/mavlink_msg_camera_settings.h \
    ../include/common/mavlink_msg_camera_settings.hpp \
    ../include/common/mavlink_msg_camera_tracking_geo_status.h \
    ../include/common/mavlink_msg_camera_tracking_geo_status.hpp \
    ../include/common/mavlink_msg_camera_tracking_image_status.h \
    ../include/common/mavlink_msg_camera_tracking_image_status.hpp \
    ../include/common/mavlink_msg_camera_trigger.h \
    ../include/common/mavlink_msg_camera_trigger.hpp \
    ../include/common/mavlink_msg_cellular_config.h \
    ../include/common/mavlink_msg_cellular_config.hpp \
    ../include/common/mavlink_msg_cellular_status.h \
    ../include/common/mavlink_msg_cellular_status.hpp \
    ../include/common/mavlink_msg_change_operator_control.h \
    ../include/common/mavlink_msg_change_operator_control.hpp \
    ../include/common/mavlink_msg_change_operator_control_ack.h \
    ../include/common/mavlink_msg_change_operator_control_ack.hpp \
    ../include/common/mavlink_msg_collision.h \
    ../include/common/mavlink_msg_collision.hpp \
    ../include/common/mavlink_msg_command_ack.h \
    ../include/common/mavlink_msg_command_ack.hpp \
    ../include/common/mavlink_msg_command_cancel.h \
    ../include/common/mavlink_msg_command_cancel.hpp \
    ../include/common/mavlink_msg_command_int.h \
    ../include/common/mavlink_msg_command_int.hpp \
    ../include/common/mavlink_msg_command_long.h \
    ../include/common/mavlink_msg_command_long.hpp \
    ../include/common/mavlink_msg_component_information.h \
    ../include/common/mavlink_msg_component_information.hpp \
    ../include/common/mavlink_msg_control_system_state.h \
    ../include/common/mavlink_msg_control_system_state.hpp \
    ../include/common/mavlink_msg_current_event_sequence.h \
    ../include/common/mavlink_msg_current_event_sequence.hpp \
    ../include/common/mavlink_msg_data_stream.h \
    ../include/common/mavlink_msg_data_stream.hpp \
    ../include/common/mavlink_msg_data_transmission_handshake.h \
    ../include/common/mavlink_msg_data_transmission_handshake.hpp \
    ../include/common/mavlink_msg_debug.h \
    ../include/common/mavlink_msg_debug.hpp \
    ../include/common/mavlink_msg_debug_float_array.h \
    ../include/common/mavlink_msg_debug_float_array.hpp \
    ../include/common/mavlink_msg_debug_vect.h \
    ../include/common/mavlink_msg_debug_vect.hpp \
    ../include/common/mavlink_msg_distance_sensor.h \
    ../include/common/mavlink_msg_distance_sensor.hpp \
    ../include/common/mavlink_msg_efi_status.h \
    ../include/common/mavlink_msg_efi_status.hpp \
    ../include/common/mavlink_msg_encapsulated_data.h \
    ../include/common/mavlink_msg_encapsulated_data.hpp \
    ../include/common/mavlink_msg_esc_info.h \
    ../include/common/mavlink_msg_esc_info.hpp \
    ../include/common/mavlink_msg_esc_status.h \
    ../include/common/mavlink_msg_esc_status.hpp \
    ../include/common/mavlink_msg_estimator_status.h \
    ../include/common/mavlink_msg_estimator_status.hpp \
    ../include/common/mavlink_msg_event.h \
    ../include/common/mavlink_msg_event.hpp \
    ../include/common/mavlink_msg_extended_sys_state.h \
    ../include/common/mavlink_msg_extended_sys_state.hpp \
    ../include/common/mavlink_msg_fence_status.h \
    ../include/common/mavlink_msg_fence_status.hpp \
    ../include/common/mavlink_msg_file_transfer_protocol.h \
    ../include/common/mavlink_msg_file_transfer_protocol.hpp \
    ../include/common/mavlink_msg_flight_information.h \
    ../include/common/mavlink_msg_flight_information.hpp \
    ../include/common/mavlink_msg_follow_target.h \
    ../include/common/mavlink_msg_follow_target.hpp \
    ../include/common/mavlink_msg_generator_status.h \
    ../include/common/mavlink_msg_generator_status.hpp \
    ../include/common/mavlink_msg_gimbal_device_attitude_status.h \
    ../include/common/mavlink_msg_gimbal_device_attitude_status.hpp \
    ../include/common/mavlink_msg_gimbal_device_information.h \
    ../include/common/mavlink_msg_gimbal_device_information.hpp \
    ../include/common/mavlink_msg_gimbal_device_set_attitude.h \
    ../include/common/mavlink_msg_gimbal_device_set_attitude.hpp \
    ../include/common/mavlink_msg_gimbal_manager_information.h \
    ../include/common/mavlink_msg_gimbal_manager_information.hpp \
    ../include/common/mavlink_msg_gimbal_manager_set_attitude.h \
    ../include/common/mavlink_msg_gimbal_manager_set_attitude.hpp \
    ../include/common/mavlink_msg_gimbal_manager_set_manual_control.h \
    ../include/common/mavlink_msg_gimbal_manager_set_manual_control.hpp \
    ../include/common/mavlink_msg_gimbal_manager_set_pitchyaw.h \
    ../include/common/mavlink_msg_gimbal_manager_set_pitchyaw.hpp \
    ../include/common/mavlink_msg_gimbal_manager_status.h \
    ../include/common/mavlink_msg_gimbal_manager_status.hpp \
    ../include/common/mavlink_msg_global_position_int.h \
    ../include/common/mavlink_msg_global_position_int.hpp \
    ../include/common/mavlink_msg_global_position_int_cov.h \
    ../include/common/mavlink_msg_global_position_int_cov.hpp \
    ../include/common/mavlink_msg_global_vision_position_estimate.h \
    ../include/common/mavlink_msg_global_vision_position_estimate.hpp \
    ../include/common/mavlink_msg_gps2_raw.h \
    ../include/common/mavlink_msg_gps2_raw.hpp \
    ../include/common/mavlink_msg_gps2_rtk.h \
    ../include/common/mavlink_msg_gps2_rtk.hpp \
    ../include/common/mavlink_msg_gps_global_origin.h \
    ../include/common/mavlink_msg_gps_global_origin.hpp \
    ../include/common/mavlink_msg_gps_inject_data.h \
    ../include/common/mavlink_msg_gps_inject_data.hpp \
    ../include/common/mavlink_msg_gps_input.h \
    ../include/common/mavlink_msg_gps_input.hpp \
    ../include/common/mavlink_msg_gps_raw_int.h \
    ../include/common/mavlink_msg_gps_raw_int.hpp \
    ../include/common/mavlink_msg_gps_rtcm_data.h \
    ../include/common/mavlink_msg_gps_rtcm_data.hpp \
    ../include/common/mavlink_msg_gps_rtk.h \
    ../include/common/mavlink_msg_gps_rtk.hpp \
    ../include/common/mavlink_msg_gps_status.h \
    ../include/common/mavlink_msg_gps_status.hpp \
    ../include/common/mavlink_msg_high_latency.h \
    ../include/common/mavlink_msg_high_latency.hpp \
    ../include/common/mavlink_msg_high_latency2.h \
    ../include/common/mavlink_msg_high_latency2.hpp \
    ../include/common/mavlink_msg_highres_imu.h \
    ../include/common/mavlink_msg_highres_imu.hpp \
    ../include/common/mavlink_msg_hil_actuator_controls.h \
    ../include/common/mavlink_msg_hil_actuator_controls.hpp \
    ../include/common/mavlink_msg_hil_controls.h \
    ../include/common/mavlink_msg_hil_controls.hpp \
    ../include/common/mavlink_msg_hil_gps.h \
    ../include/common/mavlink_msg_hil_gps.hpp \
    ../include/common/mavlink_msg_hil_optical_flow.h \
    ../include/common/mavlink_msg_hil_optical_flow.hpp \
    ../include/common/mavlink_msg_hil_rc_inputs_raw.h \
    ../include/common/mavlink_msg_hil_rc_inputs_raw.hpp \
    ../include/common/mavlink_msg_hil_sensor.h \
    ../include/common/mavlink_msg_hil_sensor.hpp \
    ../include/common/mavlink_msg_hil_state.h \
    ../include/common/mavlink_msg_hil_state.hpp \
    ../include/common/mavlink_msg_hil_state_quaternion.h \
    ../include/common/mavlink_msg_hil_state_quaternion.hpp \
    ../include/common/mavlink_msg_home_position.h \
    ../include/common/mavlink_msg_home_position.hpp \
    ../include/common/mavlink_msg_hygrometer_sensor.h \
    ../include/common/mavlink_msg_hygrometer_sensor.hpp \
    ../include/common/mavlink_msg_isbd_link_status.h \
    ../include/common/mavlink_msg_isbd_link_status.hpp \
    ../include/common/mavlink_msg_landing_target.h \
    ../include/common/mavlink_msg_landing_target.hpp \
    ../include/common/mavlink_msg_link_node_status.h \
    ../include/common/mavlink_msg_link_node_status.hpp \
    ../include/common/mavlink_msg_local_position_ned.h \
    ../include/common/mavlink_msg_local_position_ned.hpp \
    ../include/common/mavlink_msg_local_position_ned_cov.h \
    ../include/common/mavlink_msg_local_position_ned_cov.hpp \
    ../include/common/mavlink_msg_local_position_ned_system_global_offset.h \
    ../include/common/mavlink_msg_local_position_ned_system_global_offset.hpp \
    ../include/common/mavlink_msg_log_data.h \
    ../include/common/mavlink_msg_log_data.hpp \
    ../include/common/mavlink_msg_log_entry.h \
    ../include/common/mavlink_msg_log_entry.hpp \
    ../include/common/mavlink_msg_log_erase.h \
    ../include/common/mavlink_msg_log_erase.hpp \
    ../include/common/mavlink_msg_log_request_data.h \
    ../include/common/mavlink_msg_log_request_data.hpp \
    ../include/common/mavlink_msg_log_request_end.h \
    ../include/common/mavlink_msg_log_request_end.hpp \
    ../include/common/mavlink_msg_log_request_list.h \
    ../include/common/mavlink_msg_log_request_list.hpp \
    ../include/common/mavlink_msg_logging_ack.h \
    ../include/common/mavlink_msg_logging_ack.hpp \
    ../include/common/mavlink_msg_logging_data.h \
    ../include/common/mavlink_msg_logging_data.hpp \
    ../include/common/mavlink_msg_logging_data_acked.h \
    ../include/common/mavlink_msg_logging_data_acked.hpp \
    ../include/common/mavlink_msg_mag_cal_report.h \
    ../include/common/mavlink_msg_mag_cal_report.hpp \
    ../include/common/mavlink_msg_manual_control.h \
    ../include/common/mavlink_msg_manual_control.hpp \
    ../include/common/mavlink_msg_manual_setpoint.h \
    ../include/common/mavlink_msg_manual_setpoint.hpp \
    ../include/common/mavlink_msg_memory_vect.h \
    ../include/common/mavlink_msg_memory_vect.hpp \
    ../include/common/mavlink_msg_message_interval.h \
    ../include/common/mavlink_msg_message_interval.hpp \
    ../include/common/mavlink_msg_mission_ack.h \
    ../include/common/mavlink_msg_mission_ack.hpp \
    ../include/common/mavlink_msg_mission_changed.h \
    ../include/common/mavlink_msg_mission_changed.hpp \
    ../include/common/mavlink_msg_mission_clear_all.h \
    ../include/common/mavlink_msg_mission_clear_all.hpp \
    ../include/common/mavlink_msg_mission_count.h \
    ../include/common/mavlink_msg_mission_count.hpp \
    ../include/common/mavlink_msg_mission_current.h \
    ../include/common/mavlink_msg_mission_current.hpp \
    ../include/common/mavlink_msg_mission_item.h \
    ../include/common/mavlink_msg_mission_item.hpp \
    ../include/common/mavlink_msg_mission_item_int.h \
    ../include/common/mavlink_msg_mission_item_int.hpp \
    ../include/common/mavlink_msg_mission_item_reached.h \
    ../include/common/mavlink_msg_mission_item_reached.hpp \
    ../include/common/mavlink_msg_mission_request.h \
    ../include/common/mavlink_msg_mission_request.hpp \
    ../include/common/mavlink_msg_mission_request_int.h \
    ../include/common/mavlink_msg_mission_request_int.hpp \
    ../include/common/mavlink_msg_mission_request_list.h \
    ../include/common/mavlink_msg_mission_request_list.hpp \
    ../include/common/mavlink_msg_mission_request_partial_list.h \
    ../include/common/mavlink_msg_mission_request_partial_list.hpp \
    ../include/common/mavlink_msg_mission_set_current.h \
    ../include/common/mavlink_msg_mission_set_current.hpp \
    ../include/common/mavlink_msg_mission_write_partial_list.h \
    ../include/common/mavlink_msg_mission_write_partial_list.hpp \
    ../include/common/mavlink_msg_mount_orientation.h \
    ../include/common/mavlink_msg_mount_orientation.hpp \
    ../include/common/mavlink_msg_named_value_float.h \
    ../include/common/mavlink_msg_named_value_float.hpp \
    ../include/common/mavlink_msg_named_value_int.h \
    ../include/common/mavlink_msg_named_value_int.hpp \
    ../include/common/mavlink_msg_nav_controller_output.h \
    ../include/common/mavlink_msg_nav_controller_output.hpp \
    ../include/common/mavlink_msg_obstacle_distance.h \
    ../include/common/mavlink_msg_obstacle_distance.hpp \
    ../include/common/mavlink_msg_odometry.h \
    ../include/common/mavlink_msg_odometry.hpp \
    ../include/common/mavlink_msg_onboard_computer_status.h \
    ../include/common/mavlink_msg_onboard_computer_status.hpp \
    ../include/common/mavlink_msg_open_drone_id_authentication.h \
    ../include/common/mavlink_msg_open_drone_id_authentication.hpp \
    ../include/common/mavlink_msg_open_drone_id_basic_id.h \
    ../include/common/mavlink_msg_open_drone_id_basic_id.hpp \
    ../include/common/mavlink_msg_open_drone_id_location.h \
    ../include/common/mavlink_msg_open_drone_id_location.hpp \
    ../include/common/mavlink_msg_open_drone_id_message_pack.h \
    ../include/common/mavlink_msg_open_drone_id_message_pack.hpp \
    ../include/common/mavlink_msg_open_drone_id_operator_id.h \
    ../include/common/mavlink_msg_open_drone_id_operator_id.hpp \
    ../include/common/mavlink_msg_open_drone_id_self_id.h \
    ../include/common/mavlink_msg_open_drone_id_self_id.hpp \
    ../include/common/mavlink_msg_open_drone_id_system.h \
    ../include/common/mavlink_msg_open_drone_id_system.hpp \
    ../include/common/mavlink_msg_optical_flow.h \
    ../include/common/mavlink_msg_optical_flow.hpp \
    ../include/common/mavlink_msg_optical_flow_rad.h \
    ../include/common/mavlink_msg_optical_flow_rad.hpp \
    ../include/common/mavlink_msg_orbit_execution_status.h \
    ../include/common/mavlink_msg_orbit_execution_status.hpp \
    ../include/common/mavlink_msg_param_ack_transaction.h \
    ../include/common/mavlink_msg_param_ack_transaction.hpp \
    ../include/common/mavlink_msg_param_ext_ack.h \
    ../include/common/mavlink_msg_param_ext_ack.hpp \
    ../include/common/mavlink_msg_param_ext_request_list.h \
    ../include/common/mavlink_msg_param_ext_request_list.hpp \
    ../include/common/mavlink_msg_param_ext_request_read.h \
    ../include/common/mavlink_msg_param_ext_request_read.hpp \
    ../include/common/mavlink_msg_param_ext_set.h \
    ../include/common/mavlink_msg_param_ext_set.hpp \
    ../include/common/mavlink_msg_param_ext_value.h \
    ../include/common/mavlink_msg_param_ext_value.hpp \
    ../include/common/mavlink_msg_param_map_rc.h \
    ../include/common/mavlink_msg_param_map_rc.hpp \
    ../include/common/mavlink_msg_param_request_list.h \
    ../include/common/mavlink_msg_param_request_list.hpp \
    ../include/common/mavlink_msg_param_request_read.h \
    ../include/common/mavlink_msg_param_request_read.hpp \
    ../include/common/mavlink_msg_param_set.h \
    ../include/common/mavlink_msg_param_set.hpp \
    ../include/common/mavlink_msg_param_value.h \
    ../include/common/mavlink_msg_param_value.hpp \
    ../include/common/mavlink_msg_ping.h \
    ../include/common/mavlink_msg_ping.hpp \
    ../include/common/mavlink_msg_play_tune.h \
    ../include/common/mavlink_msg_play_tune.hpp \
    ../include/common/mavlink_msg_play_tune_v2.h \
    ../include/common/mavlink_msg_play_tune_v2.hpp \
    ../include/common/mavlink_msg_position_target_global_int.h \
    ../include/common/mavlink_msg_position_target_global_int.hpp \
    ../include/common/mavlink_msg_position_target_local_ned.h \
    ../include/common/mavlink_msg_position_target_local_ned.hpp \
    ../include/common/mavlink_msg_power_status.h \
    ../include/common/mavlink_msg_power_status.hpp \
    ../include/common/mavlink_msg_radio_status.h \
    ../include/common/mavlink_msg_radio_status.hpp \
    ../include/common/mavlink_msg_raw_imu.h \
    ../include/common/mavlink_msg_raw_imu.hpp \
    ../include/common/mavlink_msg_raw_pressure.h \
    ../include/common/mavlink_msg_raw_pressure.hpp \
    ../include/common/mavlink_msg_raw_rpm.h \
    ../include/common/mavlink_msg_raw_rpm.hpp \
    ../include/common/mavlink_msg_rc_channels.h \
    ../include/common/mavlink_msg_rc_channels.hpp \
    ../include/common/mavlink_msg_rc_channels_override.h \
    ../include/common/mavlink_msg_rc_channels_override.hpp \
    ../include/common/mavlink_msg_rc_channels_raw.h \
    ../include/common/mavlink_msg_rc_channels_raw.hpp \
    ../include/common/mavlink_msg_rc_channels_scaled.h \
    ../include/common/mavlink_msg_rc_channels_scaled.hpp \
    ../include/common/mavlink_msg_request_data_stream.h \
    ../include/common/mavlink_msg_request_data_stream.hpp \
    ../include/common/mavlink_msg_request_event.h \
    ../include/common/mavlink_msg_request_event.hpp \
    ../include/common/mavlink_msg_resource_request.h \
    ../include/common/mavlink_msg_resource_request.hpp \
    ../include/common/mavlink_msg_response_event_error.h \
    ../include/common/mavlink_msg_response_event_error.hpp \
    ../include/common/mavlink_msg_safety_allowed_area.h \
    ../include/common/mavlink_msg_safety_allowed_area.hpp \
    ../include/common/mavlink_msg_safety_set_allowed_area.h \
    ../include/common/mavlink_msg_safety_set_allowed_area.hpp \
    ../include/common/mavlink_msg_scaled_imu.h \
    ../include/common/mavlink_msg_scaled_imu.hpp \
    ../include/common/mavlink_msg_scaled_imu2.h \
    ../include/common/mavlink_msg_scaled_imu2.hpp \
    ../include/common/mavlink_msg_scaled_imu3.h \
    ../include/common/mavlink_msg_scaled_imu3.hpp \
    ../include/common/mavlink_msg_scaled_pressure.h \
    ../include/common/mavlink_msg_scaled_pressure.hpp \
    ../include/common/mavlink_msg_scaled_pressure2.h \
    ../include/common/mavlink_msg_scaled_pressure2.hpp \
    ../include/common/mavlink_msg_scaled_pressure3.h \
    ../include/common/mavlink_msg_scaled_pressure3.hpp \
    ../include/common/mavlink_msg_serial_control.h \
    ../include/common/mavlink_msg_serial_control.hpp \
    ../include/common/mavlink_msg_servo_output_raw.h \
    ../include/common/mavlink_msg_servo_output_raw.hpp \
    ../include/common/mavlink_msg_set_actuator_control_target.h \
    ../include/common/mavlink_msg_set_actuator_control_target.hpp \
    ../include/common/mavlink_msg_set_attitude_target.h \
    ../include/common/mavlink_msg_set_attitude_target.hpp \
    ../include/common/mavlink_msg_set_gps_global_origin.h \
    ../include/common/mavlink_msg_set_gps_global_origin.hpp \
    ../include/common/mavlink_msg_set_home_position.h \
    ../include/common/mavlink_msg_set_home_position.hpp \
    ../include/common/mavlink_msg_set_mode.h \
    ../include/common/mavlink_msg_set_mode.hpp \
    ../include/common/mavlink_msg_set_position_target_global_int.h \
    ../include/common/mavlink_msg_set_position_target_global_int.hpp \
    ../include/common/mavlink_msg_set_position_target_local_ned.h \
    ../include/common/mavlink_msg_set_position_target_local_ned.hpp \
    ../include/common/mavlink_msg_setup_signing.h \
    ../include/common/mavlink_msg_setup_signing.hpp \
    ../include/common/mavlink_msg_sim_state.h \
    ../include/common/mavlink_msg_sim_state.hpp \
    ../include/common/mavlink_msg_smart_battery_info.h \
    ../include/common/mavlink_msg_smart_battery_info.hpp \
    ../include/common/mavlink_msg_statustext.h \
    ../include/common/mavlink_msg_statustext.hpp \
    ../include/common/mavlink_msg_storage_information.h \
    ../include/common/mavlink_msg_storage_information.hpp \
    ../include/common/mavlink_msg_supported_tunes.h \
    ../include/common/mavlink_msg_supported_tunes.hpp \
    ../include/common/mavlink_msg_sys_status.h \
    ../include/common/mavlink_msg_sys_status.hpp \
    ../include/common/mavlink_msg_system_time.h \
    ../include/common/mavlink_msg_system_time.hpp \
    ../include/common/mavlink_msg_terrain_check.h \
    ../include/common/mavlink_msg_terrain_check.hpp \
    ../include/common/mavlink_msg_terrain_data.h \
    ../include/common/mavlink_msg_terrain_data.hpp \
    ../include/common/mavlink_msg_terrain_report.h \
    ../include/common/mavlink_msg_terrain_report.hpp \
    ../include/common/mavlink_msg_terrain_request.h \
    ../include/common/mavlink_msg_terrain_request.hpp \
    ../include/common/mavlink_msg_time_estimate_to_target.h \
    ../include/common/mavlink_msg_time_estimate_to_target.hpp \
    ../include/common/mavlink_msg_timesync.h \
    ../include/common/mavlink_msg_timesync.hpp \
    ../include/common/mavlink_msg_trajectory_representation_bezier.h \
    ../include/common/mavlink_msg_trajectory_representation_bezier.hpp \
    ../include/common/mavlink_msg_trajectory_representation_waypoints.h \
    ../include/common/mavlink_msg_trajectory_representation_waypoints.hpp \
    ../include/common/mavlink_msg_tunnel.h \
    ../include/common/mavlink_msg_tunnel.hpp \
    ../include/common/mavlink_msg_uavcan_node_info.h \
    ../include/common/mavlink_msg_uavcan_node_info.hpp \
    ../include/common/mavlink_msg_uavcan_node_status.h \
    ../include/common/mavlink_msg_uavcan_node_status.hpp \
    ../include/common/mavlink_msg_utm_global_position.h \
    ../include/common/mavlink_msg_utm_global_position.hpp \
    ../include/common/mavlink_msg_v2_extension.h \
    ../include/common/mavlink_msg_v2_extension.hpp \
    ../include/common/mavlink_msg_vfr_hud.h \
    ../include/common/mavlink_msg_vfr_hud.hpp \
    ../include/common/mavlink_msg_vibration.h \
    ../include/common/mavlink_msg_vibration.hpp \
    ../include/common/mavlink_msg_vicon_position_estimate.h \
    ../include/common/mavlink_msg_vicon_position_estimate.hpp \
    ../include/common/mavlink_msg_video_stream_information.h \
    ../include/common/mavlink_msg_video_stream_information.hpp \
    ../include/common/mavlink_msg_video_stream_status.h \
    ../include/common/mavlink_msg_video_stream_status.hpp \
    ../include/common/mavlink_msg_vision_position_estimate.h \
    ../include/common/mavlink_msg_vision_position_estimate.hpp \
    ../include/common/mavlink_msg_vision_speed_estimate.h \
    ../include/common/mavlink_msg_vision_speed_estimate.hpp \
    ../include/common/mavlink_msg_wheel_distance.h \
    ../include/common/mavlink_msg_wheel_distance.hpp \
    ../include/common/mavlink_msg_wifi_config_ap.h \
    ../include/common/mavlink_msg_wifi_config_ap.hpp \
    ../include/common/mavlink_msg_winch_status.h \
    ../include/common/mavlink_msg_winch_status.hpp \
    ../include/common/mavlink_msg_wind_cov.h \
    ../include/common/mavlink_msg_wind_cov.hpp \
    ../include/common/testsuite.h \
    ../include/common/version.h \
    ../include/custom/custom.h \
    ../include/custom/custom.hpp \
    ../include/custom/gtestsuite.hpp \
    ../include/custom/mavlink_msg_airspeed.h \
    ../include/custom/mavlink_msg_airspeed.hpp \
    ../include/custom/mavlink_msg_barometer.h \
    ../include/custom/mavlink_msg_barometer.hpp \
    ../include/custom/mavlink_msg_flightangles.h \
    ../include/custom/mavlink_msg_flightangles.hpp \
    ../include/custom/mavlink_msg_flightsurfaces.h \
    ../include/custom/mavlink_msg_flightsurfaces.hpp \
    ../include/custom/mavlink_msg_gps.h \
    ../include/custom/mavlink_msg_gps.hpp \
    ../include/custom/mavlink_msg_thrust.h \
    ../include/custom/mavlink_msg_thrust.hpp \
    ../include/custom/mavlink.h \
    ../include/custom/testsuite.h \
    ../include/custom/version.h \
    ../include/mavlink_conversions.h \
    ../include/mavlink_get_info.h \
    ../include/mavlink_helpers.h \
    ../include/mavlink_sha256.h \
    ../include/mavlink_types.h \
    ../include/message.hpp \
    ../include/minimal/gtestsuite.hpp \
    ../include/minimal/mavlink.h \
    ../include/minimal/mavlink_msg_heartbeat.h \
    ../include/minimal/mavlink_msg_heartbeat.hpp \
    ../include/minimal/mavlink_msg_protocol_version.h \
    ../include/minimal/mavlink_msg_protocol_version.hpp \
    ../include/minimal/minimal.h \
    ../include/minimal/minimal.hpp \
    ../include/minimal/testsuite.h \
    ../include/minimal/version.h \
    ../include/msgmap.hpp \
    ../include/protocol.h \
    ../include/standard/gtestsuite.hpp \
    ../include/standard/mavlink.h \
    ../include/standard/standard.h \
    ../include/standard/standard.hpp \
    ../include/standard/testsuite.h \
    ../include/standard/version.h \
    ../mavsys.h \
    ../messagehandler.h \
    uavmessagehandler.h \
    ../serialconnection.h \
    ../udpconnection.h
